name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v2.3.4
      - name: Cypress.io
        uses: cypress-io/github-actions@v2.9.7
        with:
            start: npm start
