name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies cache them correctly
      # and tun all cypress tests 
      - name: Setup Cypress run
        uses: cypress-io/github-actions@v5
