name: Run Cypress Tests
on:
  push:
    branches:
    - main
    - develop
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cypress
      run: npm install cypress
    - name: Run Cypress Tests
      run: cypress run
    reporting:
      always: true
